version: "3.2"
networks:
  mtgvrd_test:
services:
  db:
    image: postgres12.1
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    build:
      context: .
      dockerfile: "docker/Dockerfile_postgres"
    networks:
      - mtgvrd_test
    volumes:
      - mtgvrd_postgres_test:/var/lib/postgresql/data
    ports:
      - "5444:5432"

volumes:
  mtgvrd_postgres_test:
