version: "3.2"
networks:
  mtgvrd_test:
services:
  db:
    image: mtgvrd_db_test
    build:
      context: .
      dockerfile: "docker/Dockerfile_postgres"
    networks:
      - mtgvrd_test
    volumes:
      - mtgvrd_postgres_test:/var/lib/postgresql/data
    ports:
      - "5444:5432"

volumes:
  mtgvrd_postgres_test:
