"""test

Revision ID: c4be243762f7
Revises: 526d2f791081
Create Date: 2022-07-16 14:02:02.521261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4be243762f7'
down_revision = '526d2f791081'
branch_labels = None
depends_on = None


def upgrade():
    # If you have added a new table and it does not show up, make sure you
    # have added it to db/models/__init__.py
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('flag', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
